version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: "minhaSenhaSegura" # Senha do root
      MYSQL_DATABASE: my_database # Nome do banco de dados inicial
    ports:
      - "3306:3306" # Porta do MySQL
    volumes:
      - mysql-data:/var/lib/mysql # Volume para persistência de dados
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql # Nome do serviço do MySQL
      PMA_PORT: 3306 # Porta do MySQL
      MYSQL_ROOT_PASSWORD: "minhaSenhaSegura" # Senha do MySQL
    ports:
      - "8080:80" # Porta do phpMyAdmin
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
